spring.application.name=Fit Track

# JPA Config#
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

# JWT Config#
spring.app.jwtExpirationMs=360000
spring.app.jwtSecret=PKqMrFQtLxMEgTUdbPcC6Tf5YYRre7WB3oUf7+K4jP0=

# DB Config #
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=