name: Frontend CI

on:
  push:
    paths:
      - "apps/frontend/**"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Instalar dependências
        run: pnpm install

      - name: Rodar testes
        run: pnpm test
